name: Patch formula
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:
jobs:
  patch:
    name: Patch the formula
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout homebrew
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Generate new version
        run: python genpatch.py

      - name: Commit and push the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --staged --quiet || git commit -m "Auto-update: $(date)"
          git push

